### ISSUE TITLE
Update checkpoint info after in-memory merge

### ISSUE THREAD

**Issue by dchatel** [hako-mikan/sd-webui-supermerger#39]
Update checkpoint info after in-memory merge, such that subsequent generated images (using txt2img, img2img, ...) have the correct model information.

This can be done easily with the following changes:

in mergers.py on line 55:`    usemodelgen(theta_0,model_a,currentmodel)`

in model_util.py,
line 775: `def usemodelgen(theta_0,model_a,model_name):`
line 813: `shared.sd_model.sd_checkpoint_info.model_name = model_name`
possibly add the rest of the info aswell, and not just the model name.

**Comment by hako-mikan** [comment]
Thanks for the suggestion. It is a good idea. I have adopted and implemented it.

**Comment by Tktw** [comment]
Merge again after merging results in an error.

`Traceback (most recent call last):
  File "C:\Users\takum\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\takum\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\Users\takum\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\takum\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\takum\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\takum\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\takum\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 51, in smergegen
    result,currentmodel,modelid,theta_0 = smerge(weights_a,weights_b,model_a,model_b,model_c,base_alpha,base_beta,mode,useblocks,custom_name,save_sets,id_sets,wpresets,deep,deepprint=deepprint)
  File "C:\Users\takum\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 156, in smerge
    theta_0=load_model_weights_m(model_a,True,False,save).copy()
  File "C:\Users\takum\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 273, in load_model_weights_m
    sd_model_name = checkpoint_info.model_name
AttributeError: 'NoneType' object has no attribute 'model_name'`

**Comment by hako-mikan** [comment]
After merging in A+B, it seem to get an error when try to load model A. 
Model A is the source of the model to be loaded for generation. 
The problem seems to be caused by renaming model A. 
Therefore, I have reverted it back.
